### ISSUE TITLE
TODO: 📔 Nest.js project starter kit (TypeORM & Postgres)

### ISSUE THREAD

**Issue by mahabubx7** [mahabubx7/nestjs-starter-kit#1]
#### To be completed:

- [x] Compose Nest.js application initials!
- [x] Setup `commit-lint` for standard commit history
- [x] Setup `ESLint` & `Prettier`
- [x] Setup `husky` & `lint-staged` for lint-proof commits
- [x] Setup and config `env` variables & docker-composed instances
- [x] Setup `TypeORM` with `PostgreSQL`
- [x] Setup Validation-pipes for incoming request body
- [x] Implement User Module with CRUD
- [ ] Implement Todo Module with CRUD
- [ ] Setup `RBAC/PBAC` with `KeyCloak`
- [ ] Config **Todo with required permissions**
- [ ] Setup `Swagger` API Documentation
- [ ] Setup `Throttler` for rate-limiting

Coding with ❤️ by @mahabubx7
